{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "kcomponent-plugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 24844,
          "sha512": "7113c0ef645b055eb21ca406e6bd817f8250332446241db1d106196a8ed14235c38b0ea14ce2d175608e6d9cabe6695c578aea75bc69f56823ac7429a7fe30d7",
          "sha256": "5a284e4250d46dc2db58a4ff358468df268c186e9b9a7e51bb798a3de83674e2",
          "sha1": "9cf2653c1ec6c134d0cef68c6d384f3866175f2c",
          "md5": "129b411ba3c711bb4df96656bf0c4509"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.github.gundy",
          "module": "semver4j",
          "version": {
            "requires": "0.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 24844,
          "sha512": "7113c0ef645b055eb21ca406e6bd817f8250332446241db1d106196a8ed14235c38b0ea14ce2d175608e6d9cabe6695c578aea75bc69f56823ac7429a7fe30d7",
          "sha256": "5a284e4250d46dc2db58a4ff358468df268c186e9b9a7e51bb798a3de83674e2",
          "sha1": "9cf2653c1ec6c134d0cef68c6d384f3866175f2c",
          "md5": "129b411ba3c711bb4df96656bf0c4509"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1-sources.jar",
          "url": "kcomponent-plugin-1.0.0-beta1-sources.jar",
          "size": 4679,
          "sha512": "5f546dabcd865abd214122d781d562ed3323a96f1befa221ff46a382cbab0d7c59715cc431322314dd76659087d66b83939780a023ed7b161a456ded52a96e5c",
          "sha256": "c2811c4f0e2268d3cdaccfcb496446f0d21838793d9fb9828e032e21b6a0689c",
          "sha1": "8e7439c322017eccf23db0c065bde52da584dbea",
          "md5": "a86f5ff6d0fa23ec84a1c045f9f984ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1-javadoc.jar",
          "url": "kcomponent-plugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "ac13c25ddaa6f2f669209f274e0792b718003ab599c16a794a08377f2041f43b5a18c41dc3f88ce2ceb364e67a0effa3fb69f652027431c3bd556e350a213db9",
          "sha256": "1d475107f174f8a5f8737c256c58f436362394427cc2c4328e8eb159c465b662",
          "sha1": "15c3718849328ac19b716a59453849c2ffc02c90",
          "md5": "01fb8551c2dd9143efb849991ef4aee2"
        }
      ]
    }
  ]
}
